// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommitInfo.proto

package com.t2r.common.models.refactorings;

public final class CommitInfoOuterClass {
  private CommitInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CommitInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Models.CommitInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string commit = 1;</code>
     */
    boolean hasCommit();
    /**
     * <code>required string commit = 1;</code>
     */
    java.lang.String getCommit();
    /**
     * <code>required string commit = 1;</code>
     */
    com.google.protobuf.ByteString
        getCommitBytes();

    /**
     * <code>required int64 filesModified = 2;</code>
     */
    boolean hasFilesModified();
    /**
     * <code>required int64 filesModified = 2;</code>
     */
    long getFilesModified();

    /**
     * <code>required int64 filesAdded = 3;</code>
     */
    boolean hasFilesAdded();
    /**
     * <code>required int64 filesAdded = 3;</code>
     */
    long getFilesAdded();

    /**
     * <code>required int64 filesRemoved = 4;</code>
     */
    boolean hasFilesRemoved();
    /**
     * <code>required int64 filesRemoved = 4;</code>
     */
    long getFilesRemoved();

    /**
     * <code>required int64 filesRenamed = 5;</code>
     */
    boolean hasFilesRenamed();
    /**
     * <code>required int64 filesRenamed = 5;</code>
     */
    long getFilesRenamed();

    /**
     * <code>required bool isTypeChangeDetected = 6;</code>
     */
    boolean hasIsTypeChangeDetected();
    /**
     * <code>required bool isTypeChangeDetected = 6;</code>
     */
    boolean getIsTypeChangeDetected();

    /**
     * <code>repeated .Models.JarInfo dependencies = 7;</code>
     */
    java.util.List<com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo> 
        getDependenciesList();
    /**
     * <code>repeated .Models.JarInfo dependencies = 7;</code>
     */
    com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo getDependencies(int index);
    /**
     * <code>repeated .Models.JarInfo dependencies = 7;</code>
     */
    int getDependenciesCount();
    /**
     * <code>repeated .Models.JarInfo dependencies = 7;</code>
     */
    java.util.List<? extends com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfoOrBuilder> 
        getDependenciesOrBuilderList();
    /**
     * <code>repeated .Models.JarInfo dependencies = 7;</code>
     */
    com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfoOrBuilder getDependenciesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Models.CommitInfo}
   */
  public  static final class CommitInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Models.CommitInfo)
      CommitInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommitInfo.newBuilder() to construct.
    private CommitInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommitInfo() {
      commit_ = "";
      filesModified_ = 0L;
      filesAdded_ = 0L;
      filesRemoved_ = 0L;
      filesRenamed_ = 0L;
      isTypeChangeDetected_ = false;
      dependencies_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommitInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              commit_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              filesModified_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              filesAdded_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              filesRemoved_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              filesRenamed_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              isTypeChangeDetected_ = input.readBool();
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                dependencies_ = new java.util.ArrayList<com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo>();
                mutable_bitField0_ |= 0x00000040;
              }
              dependencies_.add(
                  input.readMessage(com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          dependencies_ = java.util.Collections.unmodifiableList(dependencies_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.t2r.common.models.refactorings.CommitInfoOuterClass.internal_static_Models_CommitInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.t2r.common.models.refactorings.CommitInfoOuterClass.internal_static_Models_CommitInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.class, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder.class);
    }

    private int bitField0_;
    public static final int COMMIT_FIELD_NUMBER = 1;
    private volatile java.lang.Object commit_;
    /**
     * <code>required string commit = 1;</code>
     */
    public boolean hasCommit() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string commit = 1;</code>
     */
    public java.lang.String getCommit() {
      java.lang.Object ref = commit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          commit_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string commit = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCommitBytes() {
      java.lang.Object ref = commit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        commit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILESMODIFIED_FIELD_NUMBER = 2;
    private long filesModified_;
    /**
     * <code>required int64 filesModified = 2;</code>
     */
    public boolean hasFilesModified() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 filesModified = 2;</code>
     */
    public long getFilesModified() {
      return filesModified_;
    }

    public static final int FILESADDED_FIELD_NUMBER = 3;
    private long filesAdded_;
    /**
     * <code>required int64 filesAdded = 3;</code>
     */
    public boolean hasFilesAdded() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 filesAdded = 3;</code>
     */
    public long getFilesAdded() {
      return filesAdded_;
    }

    public static final int FILESREMOVED_FIELD_NUMBER = 4;
    private long filesRemoved_;
    /**
     * <code>required int64 filesRemoved = 4;</code>
     */
    public boolean hasFilesRemoved() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 filesRemoved = 4;</code>
     */
    public long getFilesRemoved() {
      return filesRemoved_;
    }

    public static final int FILESRENAMED_FIELD_NUMBER = 5;
    private long filesRenamed_;
    /**
     * <code>required int64 filesRenamed = 5;</code>
     */
    public boolean hasFilesRenamed() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int64 filesRenamed = 5;</code>
     */
    public long getFilesRenamed() {
      return filesRenamed_;
    }

    public static final int ISTYPECHANGEDETECTED_FIELD_NUMBER = 6;
    private boolean isTypeChangeDetected_;
    /**
     * <code>required bool isTypeChangeDetected = 6;</code>
     */
    public boolean hasIsTypeChangeDetected() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bool isTypeChangeDetected = 6;</code>
     */
    public boolean getIsTypeChangeDetected() {
      return isTypeChangeDetected_;
    }

    public static final int DEPENDENCIES_FIELD_NUMBER = 7;
    private java.util.List<com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo> dependencies_;
    /**
     * <code>repeated .Models.JarInfo dependencies = 7;</code>
     */
    public java.util.List<com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo> getDependenciesList() {
      return dependencies_;
    }
    /**
     * <code>repeated .Models.JarInfo dependencies = 7;</code>
     */
    public java.util.List<? extends com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfoOrBuilder> 
        getDependenciesOrBuilderList() {
      return dependencies_;
    }
    /**
     * <code>repeated .Models.JarInfo dependencies = 7;</code>
     */
    public int getDependenciesCount() {
      return dependencies_.size();
    }
    /**
     * <code>repeated .Models.JarInfo dependencies = 7;</code>
     */
    public com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo getDependencies(int index) {
      return dependencies_.get(index);
    }
    /**
     * <code>repeated .Models.JarInfo dependencies = 7;</code>
     */
    public com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfoOrBuilder getDependenciesOrBuilder(
        int index) {
      return dependencies_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasCommit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFilesModified()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFilesAdded()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFilesRemoved()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFilesRenamed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsTypeChangeDetected()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getDependenciesCount(); i++) {
        if (!getDependencies(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, commit_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, filesModified_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, filesAdded_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, filesRemoved_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, filesRenamed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(6, isTypeChangeDetected_);
      }
      for (int i = 0; i < dependencies_.size(); i++) {
        output.writeMessage(7, dependencies_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, commit_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, filesModified_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, filesAdded_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, filesRemoved_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, filesRenamed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, isTypeChangeDetected_);
      }
      for (int i = 0; i < dependencies_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, dependencies_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo)) {
        return super.equals(obj);
      }
      com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo other = (com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo) obj;

      boolean result = true;
      result = result && (hasCommit() == other.hasCommit());
      if (hasCommit()) {
        result = result && getCommit()
            .equals(other.getCommit());
      }
      result = result && (hasFilesModified() == other.hasFilesModified());
      if (hasFilesModified()) {
        result = result && (getFilesModified()
            == other.getFilesModified());
      }
      result = result && (hasFilesAdded() == other.hasFilesAdded());
      if (hasFilesAdded()) {
        result = result && (getFilesAdded()
            == other.getFilesAdded());
      }
      result = result && (hasFilesRemoved() == other.hasFilesRemoved());
      if (hasFilesRemoved()) {
        result = result && (getFilesRemoved()
            == other.getFilesRemoved());
      }
      result = result && (hasFilesRenamed() == other.hasFilesRenamed());
      if (hasFilesRenamed()) {
        result = result && (getFilesRenamed()
            == other.getFilesRenamed());
      }
      result = result && (hasIsTypeChangeDetected() == other.hasIsTypeChangeDetected());
      if (hasIsTypeChangeDetected()) {
        result = result && (getIsTypeChangeDetected()
            == other.getIsTypeChangeDetected());
      }
      result = result && getDependenciesList()
          .equals(other.getDependenciesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCommit()) {
        hash = (37 * hash) + COMMIT_FIELD_NUMBER;
        hash = (53 * hash) + getCommit().hashCode();
      }
      if (hasFilesModified()) {
        hash = (37 * hash) + FILESMODIFIED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFilesModified());
      }
      if (hasFilesAdded()) {
        hash = (37 * hash) + FILESADDED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFilesAdded());
      }
      if (hasFilesRemoved()) {
        hash = (37 * hash) + FILESREMOVED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFilesRemoved());
      }
      if (hasFilesRenamed()) {
        hash = (37 * hash) + FILESRENAMED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFilesRenamed());
      }
      if (hasIsTypeChangeDetected()) {
        hash = (37 * hash) + ISTYPECHANGEDETECTED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getIsTypeChangeDetected());
      }
      if (getDependenciesCount() > 0) {
        hash = (37 * hash) + DEPENDENCIES_FIELD_NUMBER;
        hash = (53 * hash) + getDependenciesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Models.CommitInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Models.CommitInfo)
        com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.t2r.common.models.refactorings.CommitInfoOuterClass.internal_static_Models_CommitInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.t2r.common.models.refactorings.CommitInfoOuterClass.internal_static_Models_CommitInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.class, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder.class);
      }

      // Construct using com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDependenciesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        commit_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        filesModified_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        filesAdded_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        filesRemoved_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        filesRenamed_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        isTypeChangeDetected_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (dependenciesBuilder_ == null) {
          dependencies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          dependenciesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.t2r.common.models.refactorings.CommitInfoOuterClass.internal_static_Models_CommitInfo_descriptor;
      }

      public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo getDefaultInstanceForType() {
        return com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.getDefaultInstance();
      }

      public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo build() {
        com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo buildPartial() {
        com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo result = new com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.commit_ = commit_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.filesModified_ = filesModified_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.filesAdded_ = filesAdded_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.filesRemoved_ = filesRemoved_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.filesRenamed_ = filesRenamed_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.isTypeChangeDetected_ = isTypeChangeDetected_;
        if (dependenciesBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            dependencies_ = java.util.Collections.unmodifiableList(dependencies_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.dependencies_ = dependencies_;
        } else {
          result.dependencies_ = dependenciesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo) {
          return mergeFrom((com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo other) {
        if (other == com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.getDefaultInstance()) return this;
        if (other.hasCommit()) {
          bitField0_ |= 0x00000001;
          commit_ = other.commit_;
          onChanged();
        }
        if (other.hasFilesModified()) {
          setFilesModified(other.getFilesModified());
        }
        if (other.hasFilesAdded()) {
          setFilesAdded(other.getFilesAdded());
        }
        if (other.hasFilesRemoved()) {
          setFilesRemoved(other.getFilesRemoved());
        }
        if (other.hasFilesRenamed()) {
          setFilesRenamed(other.getFilesRenamed());
        }
        if (other.hasIsTypeChangeDetected()) {
          setIsTypeChangeDetected(other.getIsTypeChangeDetected());
        }
        if (dependenciesBuilder_ == null) {
          if (!other.dependencies_.isEmpty()) {
            if (dependencies_.isEmpty()) {
              dependencies_ = other.dependencies_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureDependenciesIsMutable();
              dependencies_.addAll(other.dependencies_);
            }
            onChanged();
          }
        } else {
          if (!other.dependencies_.isEmpty()) {
            if (dependenciesBuilder_.isEmpty()) {
              dependenciesBuilder_.dispose();
              dependenciesBuilder_ = null;
              dependencies_ = other.dependencies_;
              bitField0_ = (bitField0_ & ~0x00000040);
              dependenciesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDependenciesFieldBuilder() : null;
            } else {
              dependenciesBuilder_.addAllMessages(other.dependencies_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCommit()) {
          return false;
        }
        if (!hasFilesModified()) {
          return false;
        }
        if (!hasFilesAdded()) {
          return false;
        }
        if (!hasFilesRemoved()) {
          return false;
        }
        if (!hasFilesRenamed()) {
          return false;
        }
        if (!hasIsTypeChangeDetected()) {
          return false;
        }
        for (int i = 0; i < getDependenciesCount(); i++) {
          if (!getDependencies(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object commit_ = "";
      /**
       * <code>required string commit = 1;</code>
       */
      public boolean hasCommit() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string commit = 1;</code>
       */
      public java.lang.String getCommit() {
        java.lang.Object ref = commit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            commit_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string commit = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCommitBytes() {
        java.lang.Object ref = commit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          commit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string commit = 1;</code>
       */
      public Builder setCommit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        commit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string commit = 1;</code>
       */
      public Builder clearCommit() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commit_ = getDefaultInstance().getCommit();
        onChanged();
        return this;
      }
      /**
       * <code>required string commit = 1;</code>
       */
      public Builder setCommitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        commit_ = value;
        onChanged();
        return this;
      }

      private long filesModified_ ;
      /**
       * <code>required int64 filesModified = 2;</code>
       */
      public boolean hasFilesModified() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 filesModified = 2;</code>
       */
      public long getFilesModified() {
        return filesModified_;
      }
      /**
       * <code>required int64 filesModified = 2;</code>
       */
      public Builder setFilesModified(long value) {
        bitField0_ |= 0x00000002;
        filesModified_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 filesModified = 2;</code>
       */
      public Builder clearFilesModified() {
        bitField0_ = (bitField0_ & ~0x00000002);
        filesModified_ = 0L;
        onChanged();
        return this;
      }

      private long filesAdded_ ;
      /**
       * <code>required int64 filesAdded = 3;</code>
       */
      public boolean hasFilesAdded() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 filesAdded = 3;</code>
       */
      public long getFilesAdded() {
        return filesAdded_;
      }
      /**
       * <code>required int64 filesAdded = 3;</code>
       */
      public Builder setFilesAdded(long value) {
        bitField0_ |= 0x00000004;
        filesAdded_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 filesAdded = 3;</code>
       */
      public Builder clearFilesAdded() {
        bitField0_ = (bitField0_ & ~0x00000004);
        filesAdded_ = 0L;
        onChanged();
        return this;
      }

      private long filesRemoved_ ;
      /**
       * <code>required int64 filesRemoved = 4;</code>
       */
      public boolean hasFilesRemoved() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 filesRemoved = 4;</code>
       */
      public long getFilesRemoved() {
        return filesRemoved_;
      }
      /**
       * <code>required int64 filesRemoved = 4;</code>
       */
      public Builder setFilesRemoved(long value) {
        bitField0_ |= 0x00000008;
        filesRemoved_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 filesRemoved = 4;</code>
       */
      public Builder clearFilesRemoved() {
        bitField0_ = (bitField0_ & ~0x00000008);
        filesRemoved_ = 0L;
        onChanged();
        return this;
      }

      private long filesRenamed_ ;
      /**
       * <code>required int64 filesRenamed = 5;</code>
       */
      public boolean hasFilesRenamed() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int64 filesRenamed = 5;</code>
       */
      public long getFilesRenamed() {
        return filesRenamed_;
      }
      /**
       * <code>required int64 filesRenamed = 5;</code>
       */
      public Builder setFilesRenamed(long value) {
        bitField0_ |= 0x00000010;
        filesRenamed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 filesRenamed = 5;</code>
       */
      public Builder clearFilesRenamed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        filesRenamed_ = 0L;
        onChanged();
        return this;
      }

      private boolean isTypeChangeDetected_ ;
      /**
       * <code>required bool isTypeChangeDetected = 6;</code>
       */
      public boolean hasIsTypeChangeDetected() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bool isTypeChangeDetected = 6;</code>
       */
      public boolean getIsTypeChangeDetected() {
        return isTypeChangeDetected_;
      }
      /**
       * <code>required bool isTypeChangeDetected = 6;</code>
       */
      public Builder setIsTypeChangeDetected(boolean value) {
        bitField0_ |= 0x00000020;
        isTypeChangeDetected_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isTypeChangeDetected = 6;</code>
       */
      public Builder clearIsTypeChangeDetected() {
        bitField0_ = (bitField0_ & ~0x00000020);
        isTypeChangeDetected_ = false;
        onChanged();
        return this;
      }

      private java.util.List<com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo> dependencies_ =
        java.util.Collections.emptyList();
      private void ensureDependenciesIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          dependencies_ = new java.util.ArrayList<com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo>(dependencies_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo, com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.Builder, com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfoOrBuilder> dependenciesBuilder_;

      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public java.util.List<com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo> getDependenciesList() {
        if (dependenciesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dependencies_);
        } else {
          return dependenciesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public int getDependenciesCount() {
        if (dependenciesBuilder_ == null) {
          return dependencies_.size();
        } else {
          return dependenciesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo getDependencies(int index) {
        if (dependenciesBuilder_ == null) {
          return dependencies_.get(index);
        } else {
          return dependenciesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public Builder setDependencies(
          int index, com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo value) {
        if (dependenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDependenciesIsMutable();
          dependencies_.set(index, value);
          onChanged();
        } else {
          dependenciesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public Builder setDependencies(
          int index, com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.Builder builderForValue) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.set(index, builderForValue.build());
          onChanged();
        } else {
          dependenciesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public Builder addDependencies(com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo value) {
        if (dependenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDependenciesIsMutable();
          dependencies_.add(value);
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public Builder addDependencies(
          int index, com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo value) {
        if (dependenciesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDependenciesIsMutable();
          dependencies_.add(index, value);
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public Builder addDependencies(
          com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.Builder builderForValue) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.add(builderForValue.build());
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public Builder addDependencies(
          int index, com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.Builder builderForValue) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.add(index, builderForValue.build());
          onChanged();
        } else {
          dependenciesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public Builder addAllDependencies(
          java.lang.Iterable<? extends com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo> values) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dependencies_);
          onChanged();
        } else {
          dependenciesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public Builder clearDependencies() {
        if (dependenciesBuilder_ == null) {
          dependencies_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          dependenciesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public Builder removeDependencies(int index) {
        if (dependenciesBuilder_ == null) {
          ensureDependenciesIsMutable();
          dependencies_.remove(index);
          onChanged();
        } else {
          dependenciesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.Builder getDependenciesBuilder(
          int index) {
        return getDependenciesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfoOrBuilder getDependenciesOrBuilder(
          int index) {
        if (dependenciesBuilder_ == null) {
          return dependencies_.get(index);  } else {
          return dependenciesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public java.util.List<? extends com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfoOrBuilder> 
           getDependenciesOrBuilderList() {
        if (dependenciesBuilder_ != null) {
          return dependenciesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dependencies_);
        }
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.Builder addDependenciesBuilder() {
        return getDependenciesFieldBuilder().addBuilder(
            com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.Builder addDependenciesBuilder(
          int index) {
        return getDependenciesFieldBuilder().addBuilder(
            index, com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .Models.JarInfo dependencies = 7;</code>
       */
      public java.util.List<com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.Builder> 
           getDependenciesBuilderList() {
        return getDependenciesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo, com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.Builder, com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfoOrBuilder> 
          getDependenciesFieldBuilder() {
        if (dependenciesBuilder_ == null) {
          dependenciesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo, com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfo.Builder, com.t2r.common.models.refactorings.JarInfoOuterClass.JarInfoOrBuilder>(
                  dependencies_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          dependencies_ = null;
        }
        return dependenciesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Models.CommitInfo)
    }

    // @@protoc_insertion_point(class_scope:Models.CommitInfo)
    private static final com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo();
    }

    public static com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<CommitInfo>
        PARSER = new com.google.protobuf.AbstractParser<CommitInfo>() {
      public CommitInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CommitInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommitInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommitInfo> getParserForType() {
      return PARSER;
    }

    public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_CommitInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_CommitInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020CommitInfo.proto\022\006Models\032\rJarInfo.prot" +
      "o\"\270\001\n\nCommitInfo\022\016\n\006commit\030\001 \002(\t\022\025\n\rfile" +
      "sModified\030\002 \002(\003\022\022\n\nfilesAdded\030\003 \002(\003\022\024\n\014f" +
      "ilesRemoved\030\004 \002(\003\022\024\n\014filesRenamed\030\005 \002(\003\022" +
      "\034\n\024isTypeChangeDetected\030\006 \002(\010\022%\n\014depende" +
      "ncies\030\007 \003(\0132\017.Models.JarInfoB$\n\"com.t2r." +
      "common.models.refactorings"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.t2r.common.models.refactorings.JarInfoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Models_CommitInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Models_CommitInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_CommitInfo_descriptor,
        new java.lang.String[] { "Commit", "FilesModified", "FilesAdded", "FilesRemoved", "FilesRenamed", "IsTypeChangeDetected", "Dependencies", });
    com.t2r.common.models.refactorings.JarInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
