// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RMined.proto

package com.t2r.common.models.refactorings;

public final class RMinedOuterClass {
  private RMinedOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RMinedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Models.RMined)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string project = 3;</code>
     */
    boolean hasProject();
    /**
     * <code>required string project = 3;</code>
     */
    java.lang.String getProject();
    /**
     * <code>required string project = 3;</code>
     */
    com.google.protobuf.ByteString
        getProjectBytes();

    /**
     * <code>required .Models.CommitInfo commit = 2;</code>
     */
    boolean hasCommit();
    /**
     * <code>required .Models.CommitInfo commit = 2;</code>
     */
    com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo getCommit();
    /**
     * <code>required .Models.CommitInfo commit = 2;</code>
     */
    com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder getCommitOrBuilder();

    /**
     * <code>map&lt;string, int64&gt; refactorings = 1;</code>
     */
    int getRefactoringsCount();
    /**
     * <code>map&lt;string, int64&gt; refactorings = 1;</code>
     */
    boolean containsRefactorings(
        java.lang.String key);
    /**
     * Use {@link #getRefactoringsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Long>
    getRefactorings();
    /**
     * <code>map&lt;string, int64&gt; refactorings = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.Long>
    getRefactoringsMap();
    /**
     * <code>map&lt;string, int64&gt; refactorings = 1;</code>
     */

    long getRefactoringsOrDefault(
        java.lang.String key,
        long defaultValue);
    /**
     * <code>map&lt;string, int64&gt; refactorings = 1;</code>
     */

    long getRefactoringsOrThrow(
        java.lang.String key);

    /**
     * <code>optional bool timeOut = 7;</code>
     */
    boolean hasTimeOut();
    /**
     * <code>optional bool timeOut = 7;</code>
     */
    boolean getTimeOut();

    /**
     * <code>optional string exception = 6;</code>
     */
    boolean hasException();
    /**
     * <code>optional string exception = 6;</code>
     */
    java.lang.String getException();
    /**
     * <code>optional string exception = 6;</code>
     */
    com.google.protobuf.ByteString
        getExceptionBytes();
  }
  /**
   * Protobuf type {@code Models.RMined}
   */
  public  static final class RMined extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Models.RMined)
      RMinedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RMined.newBuilder() to construct.
    private RMined(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RMined() {
      project_ = "";
      timeOut_ = false;
      exception_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RMined(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                refactorings_ = com.google.protobuf.MapField.newMapField(
                    RefactoringsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
              refactorings__ = input.readMessage(
                  RefactoringsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              refactorings_.getMutableMap().put(
                  refactorings__.getKey(), refactorings__.getValue());
              break;
            }
            case 18: {
              com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = commit_.toBuilder();
              }
              commit_ = input.readMessage(com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(commit_);
                commit_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              project_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              exception_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000004;
              timeOut_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.t2r.common.models.refactorings.RMinedOuterClass.internal_static_Models_RMined_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetRefactorings();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.t2r.common.models.refactorings.RMinedOuterClass.internal_static_Models_RMined_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.t2r.common.models.refactorings.RMinedOuterClass.RMined.class, com.t2r.common.models.refactorings.RMinedOuterClass.RMined.Builder.class);
    }

    private int bitField0_;
    public static final int PROJECT_FIELD_NUMBER = 3;
    private volatile java.lang.Object project_;
    /**
     * <code>required string project = 3;</code>
     */
    public boolean hasProject() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string project = 3;</code>
     */
    public java.lang.String getProject() {
      java.lang.Object ref = project_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          project_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string project = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProjectBytes() {
      java.lang.Object ref = project_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        project_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMIT_FIELD_NUMBER = 2;
    private com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo commit_;
    /**
     * <code>required .Models.CommitInfo commit = 2;</code>
     */
    public boolean hasCommit() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .Models.CommitInfo commit = 2;</code>
     */
    public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo getCommit() {
      return commit_ == null ? com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.getDefaultInstance() : commit_;
    }
    /**
     * <code>required .Models.CommitInfo commit = 2;</code>
     */
    public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder getCommitOrBuilder() {
      return commit_ == null ? com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.getDefaultInstance() : commit_;
    }

    public static final int REFACTORINGS_FIELD_NUMBER = 1;
    private static final class RefactoringsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Long> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Long>newDefaultInstance(
                  com.t2r.common.models.refactorings.RMinedOuterClass.internal_static_Models_RMined_RefactoringsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Long> refactorings_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
    internalGetRefactorings() {
      if (refactorings_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            RefactoringsDefaultEntryHolder.defaultEntry);
      }
      return refactorings_;
    }

    public int getRefactoringsCount() {
      return internalGetRefactorings().getMap().size();
    }
    /**
     * <code>map&lt;string, int64&gt; refactorings = 1;</code>
     */

    public boolean containsRefactorings(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetRefactorings().getMap().containsKey(key);
    }
    /**
     * Use {@link #getRefactoringsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Long> getRefactorings() {
      return getRefactoringsMap();
    }
    /**
     * <code>map&lt;string, int64&gt; refactorings = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Long> getRefactoringsMap() {
      return internalGetRefactorings().getMap();
    }
    /**
     * <code>map&lt;string, int64&gt; refactorings = 1;</code>
     */

    public long getRefactoringsOrDefault(
        java.lang.String key,
        long defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetRefactorings().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, int64&gt; refactorings = 1;</code>
     */

    public long getRefactoringsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Long> map =
          internalGetRefactorings().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int TIMEOUT_FIELD_NUMBER = 7;
    private boolean timeOut_;
    /**
     * <code>optional bool timeOut = 7;</code>
     */
    public boolean hasTimeOut() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool timeOut = 7;</code>
     */
    public boolean getTimeOut() {
      return timeOut_;
    }

    public static final int EXCEPTION_FIELD_NUMBER = 6;
    private volatile java.lang.Object exception_;
    /**
     * <code>optional string exception = 6;</code>
     */
    public boolean hasException() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string exception = 6;</code>
     */
    public java.lang.String getException() {
      java.lang.Object ref = exception_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          exception_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string exception = 6;</code>
     */
    public com.google.protobuf.ByteString
        getExceptionBytes() {
      java.lang.Object ref = exception_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exception_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProject()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCommit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getCommit().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetRefactorings(),
          RefactoringsDefaultEntryHolder.defaultEntry,
          1);
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getCommit());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, project_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, exception_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(7, timeOut_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Long> entry
           : internalGetRefactorings().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Long>
        refactorings__ = RefactoringsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, refactorings__);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCommit());
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, project_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, exception_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, timeOut_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.t2r.common.models.refactorings.RMinedOuterClass.RMined)) {
        return super.equals(obj);
      }
      com.t2r.common.models.refactorings.RMinedOuterClass.RMined other = (com.t2r.common.models.refactorings.RMinedOuterClass.RMined) obj;

      boolean result = true;
      result = result && (hasProject() == other.hasProject());
      if (hasProject()) {
        result = result && getProject()
            .equals(other.getProject());
      }
      result = result && (hasCommit() == other.hasCommit());
      if (hasCommit()) {
        result = result && getCommit()
            .equals(other.getCommit());
      }
      result = result && internalGetRefactorings().equals(
          other.internalGetRefactorings());
      result = result && (hasTimeOut() == other.hasTimeOut());
      if (hasTimeOut()) {
        result = result && (getTimeOut()
            == other.getTimeOut());
      }
      result = result && (hasException() == other.hasException());
      if (hasException()) {
        result = result && getException()
            .equals(other.getException());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProject()) {
        hash = (37 * hash) + PROJECT_FIELD_NUMBER;
        hash = (53 * hash) + getProject().hashCode();
      }
      if (hasCommit()) {
        hash = (37 * hash) + COMMIT_FIELD_NUMBER;
        hash = (53 * hash) + getCommit().hashCode();
      }
      if (!internalGetRefactorings().getMap().isEmpty()) {
        hash = (37 * hash) + REFACTORINGS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetRefactorings().hashCode();
      }
      if (hasTimeOut()) {
        hash = (37 * hash) + TIMEOUT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getTimeOut());
      }
      if (hasException()) {
        hash = (37 * hash) + EXCEPTION_FIELD_NUMBER;
        hash = (53 * hash) + getException().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.t2r.common.models.refactorings.RMinedOuterClass.RMined prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Models.RMined}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Models.RMined)
        com.t2r.common.models.refactorings.RMinedOuterClass.RMinedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.t2r.common.models.refactorings.RMinedOuterClass.internal_static_Models_RMined_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetRefactorings();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableRefactorings();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.t2r.common.models.refactorings.RMinedOuterClass.internal_static_Models_RMined_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.t2r.common.models.refactorings.RMinedOuterClass.RMined.class, com.t2r.common.models.refactorings.RMinedOuterClass.RMined.Builder.class);
      }

      // Construct using com.t2r.common.models.refactorings.RMinedOuterClass.RMined.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCommitFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        project_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (commitBuilder_ == null) {
          commit_ = null;
        } else {
          commitBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableRefactorings().clear();
        timeOut_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        exception_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.t2r.common.models.refactorings.RMinedOuterClass.internal_static_Models_RMined_descriptor;
      }

      public com.t2r.common.models.refactorings.RMinedOuterClass.RMined getDefaultInstanceForType() {
        return com.t2r.common.models.refactorings.RMinedOuterClass.RMined.getDefaultInstance();
      }

      public com.t2r.common.models.refactorings.RMinedOuterClass.RMined build() {
        com.t2r.common.models.refactorings.RMinedOuterClass.RMined result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.t2r.common.models.refactorings.RMinedOuterClass.RMined buildPartial() {
        com.t2r.common.models.refactorings.RMinedOuterClass.RMined result = new com.t2r.common.models.refactorings.RMinedOuterClass.RMined(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.project_ = project_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (commitBuilder_ == null) {
          result.commit_ = commit_;
        } else {
          result.commit_ = commitBuilder_.build();
        }
        result.refactorings_ = internalGetRefactorings();
        result.refactorings_.makeImmutable();
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timeOut_ = timeOut_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.exception_ = exception_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.t2r.common.models.refactorings.RMinedOuterClass.RMined) {
          return mergeFrom((com.t2r.common.models.refactorings.RMinedOuterClass.RMined)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.t2r.common.models.refactorings.RMinedOuterClass.RMined other) {
        if (other == com.t2r.common.models.refactorings.RMinedOuterClass.RMined.getDefaultInstance()) return this;
        if (other.hasProject()) {
          bitField0_ |= 0x00000001;
          project_ = other.project_;
          onChanged();
        }
        if (other.hasCommit()) {
          mergeCommit(other.getCommit());
        }
        internalGetMutableRefactorings().mergeFrom(
            other.internalGetRefactorings());
        if (other.hasTimeOut()) {
          setTimeOut(other.getTimeOut());
        }
        if (other.hasException()) {
          bitField0_ |= 0x00000010;
          exception_ = other.exception_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasProject()) {
          return false;
        }
        if (!hasCommit()) {
          return false;
        }
        if (!getCommit().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.t2r.common.models.refactorings.RMinedOuterClass.RMined parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.t2r.common.models.refactorings.RMinedOuterClass.RMined) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object project_ = "";
      /**
       * <code>required string project = 3;</code>
       */
      public boolean hasProject() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string project = 3;</code>
       */
      public java.lang.String getProject() {
        java.lang.Object ref = project_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            project_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string project = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProjectBytes() {
        java.lang.Object ref = project_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          project_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string project = 3;</code>
       */
      public Builder setProject(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        project_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string project = 3;</code>
       */
      public Builder clearProject() {
        bitField0_ = (bitField0_ & ~0x00000001);
        project_ = getDefaultInstance().getProject();
        onChanged();
        return this;
      }
      /**
       * <code>required string project = 3;</code>
       */
      public Builder setProjectBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        project_ = value;
        onChanged();
        return this;
      }

      private com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo commit_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder> commitBuilder_;
      /**
       * <code>required .Models.CommitInfo commit = 2;</code>
       */
      public boolean hasCommit() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .Models.CommitInfo commit = 2;</code>
       */
      public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo getCommit() {
        if (commitBuilder_ == null) {
          return commit_ == null ? com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.getDefaultInstance() : commit_;
        } else {
          return commitBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Models.CommitInfo commit = 2;</code>
       */
      public Builder setCommit(com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo value) {
        if (commitBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          commit_ = value;
          onChanged();
        } else {
          commitBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Models.CommitInfo commit = 2;</code>
       */
      public Builder setCommit(
          com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder builderForValue) {
        if (commitBuilder_ == null) {
          commit_ = builderForValue.build();
          onChanged();
        } else {
          commitBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Models.CommitInfo commit = 2;</code>
       */
      public Builder mergeCommit(com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo value) {
        if (commitBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              commit_ != null &&
              commit_ != com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.getDefaultInstance()) {
            commit_ =
              com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.newBuilder(commit_).mergeFrom(value).buildPartial();
          } else {
            commit_ = value;
          }
          onChanged();
        } else {
          commitBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>required .Models.CommitInfo commit = 2;</code>
       */
      public Builder clearCommit() {
        if (commitBuilder_ == null) {
          commit_ = null;
          onChanged();
        } else {
          commitBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>required .Models.CommitInfo commit = 2;</code>
       */
      public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder getCommitBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCommitFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Models.CommitInfo commit = 2;</code>
       */
      public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder getCommitOrBuilder() {
        if (commitBuilder_ != null) {
          return commitBuilder_.getMessageOrBuilder();
        } else {
          return commit_ == null ?
              com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.getDefaultInstance() : commit_;
        }
      }
      /**
       * <code>required .Models.CommitInfo commit = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder> 
          getCommitFieldBuilder() {
        if (commitBuilder_ == null) {
          commitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder>(
                  getCommit(),
                  getParentForChildren(),
                  isClean());
          commit_ = null;
        }
        return commitBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Long> refactorings_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
      internalGetRefactorings() {
        if (refactorings_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              RefactoringsDefaultEntryHolder.defaultEntry);
        }
        return refactorings_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Long>
      internalGetMutableRefactorings() {
        onChanged();;
        if (refactorings_ == null) {
          refactorings_ = com.google.protobuf.MapField.newMapField(
              RefactoringsDefaultEntryHolder.defaultEntry);
        }
        if (!refactorings_.isMutable()) {
          refactorings_ = refactorings_.copy();
        }
        return refactorings_;
      }

      public int getRefactoringsCount() {
        return internalGetRefactorings().getMap().size();
      }
      /**
       * <code>map&lt;string, int64&gt; refactorings = 1;</code>
       */

      public boolean containsRefactorings(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetRefactorings().getMap().containsKey(key);
      }
      /**
       * Use {@link #getRefactoringsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Long> getRefactorings() {
        return getRefactoringsMap();
      }
      /**
       * <code>map&lt;string, int64&gt; refactorings = 1;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Long> getRefactoringsMap() {
        return internalGetRefactorings().getMap();
      }
      /**
       * <code>map&lt;string, int64&gt; refactorings = 1;</code>
       */

      public long getRefactoringsOrDefault(
          java.lang.String key,
          long defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Long> map =
            internalGetRefactorings().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, int64&gt; refactorings = 1;</code>
       */

      public long getRefactoringsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Long> map =
            internalGetRefactorings().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearRefactorings() {
        internalGetMutableRefactorings().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, int64&gt; refactorings = 1;</code>
       */

      public Builder removeRefactorings(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableRefactorings().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Long>
      getMutableRefactorings() {
        return internalGetMutableRefactorings().getMutableMap();
      }
      /**
       * <code>map&lt;string, int64&gt; refactorings = 1;</code>
       */
      public Builder putRefactorings(
          java.lang.String key,
          long value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableRefactorings().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, int64&gt; refactorings = 1;</code>
       */

      public Builder putAllRefactorings(
          java.util.Map<java.lang.String, java.lang.Long> values) {
        internalGetMutableRefactorings().getMutableMap()
            .putAll(values);
        return this;
      }

      private boolean timeOut_ ;
      /**
       * <code>optional bool timeOut = 7;</code>
       */
      public boolean hasTimeOut() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool timeOut = 7;</code>
       */
      public boolean getTimeOut() {
        return timeOut_;
      }
      /**
       * <code>optional bool timeOut = 7;</code>
       */
      public Builder setTimeOut(boolean value) {
        bitField0_ |= 0x00000008;
        timeOut_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool timeOut = 7;</code>
       */
      public Builder clearTimeOut() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timeOut_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object exception_ = "";
      /**
       * <code>optional string exception = 6;</code>
       */
      public boolean hasException() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string exception = 6;</code>
       */
      public java.lang.String getException() {
        java.lang.Object ref = exception_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            exception_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string exception = 6;</code>
       */
      public com.google.protobuf.ByteString
          getExceptionBytes() {
        java.lang.Object ref = exception_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exception_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string exception = 6;</code>
       */
      public Builder setException(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exception_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string exception = 6;</code>
       */
      public Builder clearException() {
        bitField0_ = (bitField0_ & ~0x00000010);
        exception_ = getDefaultInstance().getException();
        onChanged();
        return this;
      }
      /**
       * <code>optional string exception = 6;</code>
       */
      public Builder setExceptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        exception_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Models.RMined)
    }

    // @@protoc_insertion_point(class_scope:Models.RMined)
    private static final com.t2r.common.models.refactorings.RMinedOuterClass.RMined DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.t2r.common.models.refactorings.RMinedOuterClass.RMined();
    }

    public static com.t2r.common.models.refactorings.RMinedOuterClass.RMined getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RMined>
        PARSER = new com.google.protobuf.AbstractParser<RMined>() {
      public RMined parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RMined(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RMined> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RMined> getParserForType() {
      return PARSER;
    }

    public com.t2r.common.models.refactorings.RMinedOuterClass.RMined getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_RMined_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_RMined_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_RMined_RefactoringsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_RMined_RefactoringsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014RMined.proto\022\006Models\032\020CommitInfo.proto" +
      "\"\316\001\n\006RMined\022\017\n\007project\030\003 \002(\t\022\"\n\006commit\030\002" +
      " \002(\0132\022.Models.CommitInfo\0226\n\014refactorings" +
      "\030\001 \003(\0132 .Models.RMined.RefactoringsEntry" +
      "\022\017\n\007timeOut\030\007 \001(\010\022\021\n\texception\030\006 \001(\t\0323\n\021" +
      "RefactoringsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030" +
      "\002 \001(\003:\0028\001B$\n\"com.t2r.common.models.refac" +
      "torings"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.t2r.common.models.refactorings.CommitInfoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Models_RMined_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Models_RMined_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_RMined_descriptor,
        new java.lang.String[] { "Project", "Commit", "Refactorings", "TimeOut", "Exception", });
    internal_static_Models_RMined_RefactoringsEntry_descriptor =
      internal_static_Models_RMined_descriptor.getNestedTypes().get(0);
    internal_static_Models_RMined_RefactoringsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_RMined_RefactoringsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.t2r.common.models.refactorings.CommitInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
