// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TypeChangeCommit.proto

package com.t2r.common.models.refactorings;

public final class TypeChangeCommitOuterClass {
  private TypeChangeCommitOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TypeChangeCommitOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TypeChangeCommit)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
     */
    java.util.List<com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis> 
        getTypeChangesList();
    /**
     * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
     */
    com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis getTypeChanges(int index);
    /**
     * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
     */
    int getTypeChangesCount();
    /**
     * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
     */
    java.util.List<? extends com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysisOrBuilder> 
        getTypeChangesOrBuilderList();
    /**
     * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
     */
    com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysisOrBuilder getTypeChangesOrBuilder(
        int index);

    /**
     * <code>.CodeStatistics codeStatistics = 2;</code>
     * @return Whether the codeStatistics field is set.
     */
    boolean hasCodeStatistics();
    /**
     * <code>.CodeStatistics codeStatistics = 2;</code>
     * @return The codeStatistics.
     */
    com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics getCodeStatistics();
    /**
     * <code>.CodeStatistics codeStatistics = 2;</code>
     */
    com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatisticsOrBuilder getCodeStatisticsOrBuilder();

    /**
     * <code>.CommitInfo commit = 3;</code>
     * @return Whether the commit field is set.
     */
    boolean hasCommit();
    /**
     * <code>.CommitInfo commit = 3;</code>
     * @return The commit.
     */
    com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo getCommit();
    /**
     * <code>.CommitInfo commit = 3;</code>
     */
    com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder getCommitOrBuilder();
  }
  /**
   * Protobuf type {@code TypeChangeCommit}
   */
  public  static final class TypeChangeCommit extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TypeChangeCommit)
      TypeChangeCommitOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TypeChangeCommit.newBuilder() to construct.
    private TypeChangeCommit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TypeChangeCommit() {
      typeChanges_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TypeChangeCommit();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TypeChangeCommit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                typeChanges_ = new java.util.ArrayList<com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis>();
                mutable_bitField0_ |= 0x00000001;
              }
              typeChanges_.add(
                  input.readMessage(com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.parser(), extensionRegistry));
              break;
            }
            case 18: {
              com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics.Builder subBuilder = null;
              if (codeStatistics_ != null) {
                subBuilder = codeStatistics_.toBuilder();
              }
              codeStatistics_ = input.readMessage(com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(codeStatistics_);
                codeStatistics_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder subBuilder = null;
              if (commit_ != null) {
                subBuilder = commit_.toBuilder();
              }
              commit_ = input.readMessage(com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(commit_);
                commit_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          typeChanges_ = java.util.Collections.unmodifiableList(typeChanges_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.internal_static_TypeChangeCommit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.internal_static_TypeChangeCommit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit.class, com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit.Builder.class);
    }

    public static final int TYPECHANGES_FIELD_NUMBER = 1;
    private java.util.List<com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis> typeChanges_;
    /**
     * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
     */
    public java.util.List<com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis> getTypeChangesList() {
      return typeChanges_;
    }
    /**
     * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
     */
    public java.util.List<? extends com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysisOrBuilder> 
        getTypeChangesOrBuilderList() {
      return typeChanges_;
    }
    /**
     * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
     */
    public int getTypeChangesCount() {
      return typeChanges_.size();
    }
    /**
     * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
     */
    public com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis getTypeChanges(int index) {
      return typeChanges_.get(index);
    }
    /**
     * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
     */
    public com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysisOrBuilder getTypeChangesOrBuilder(
        int index) {
      return typeChanges_.get(index);
    }

    public static final int CODESTATISTICS_FIELD_NUMBER = 2;
    private com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics codeStatistics_;
    /**
     * <code>.CodeStatistics codeStatistics = 2;</code>
     * @return Whether the codeStatistics field is set.
     */
    public boolean hasCodeStatistics() {
      return codeStatistics_ != null;
    }
    /**
     * <code>.CodeStatistics codeStatistics = 2;</code>
     * @return The codeStatistics.
     */
    public com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics getCodeStatistics() {
      return codeStatistics_ == null ? com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics.getDefaultInstance() : codeStatistics_;
    }
    /**
     * <code>.CodeStatistics codeStatistics = 2;</code>
     */
    public com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatisticsOrBuilder getCodeStatisticsOrBuilder() {
      return getCodeStatistics();
    }

    public static final int COMMIT_FIELD_NUMBER = 3;
    private com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo commit_;
    /**
     * <code>.CommitInfo commit = 3;</code>
     * @return Whether the commit field is set.
     */
    public boolean hasCommit() {
      return commit_ != null;
    }
    /**
     * <code>.CommitInfo commit = 3;</code>
     * @return The commit.
     */
    public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo getCommit() {
      return commit_ == null ? com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.getDefaultInstance() : commit_;
    }
    /**
     * <code>.CommitInfo commit = 3;</code>
     */
    public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder getCommitOrBuilder() {
      return getCommit();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < typeChanges_.size(); i++) {
        output.writeMessage(1, typeChanges_.get(i));
      }
      if (codeStatistics_ != null) {
        output.writeMessage(2, getCodeStatistics());
      }
      if (commit_ != null) {
        output.writeMessage(3, getCommit());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < typeChanges_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, typeChanges_.get(i));
      }
      if (codeStatistics_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCodeStatistics());
      }
      if (commit_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCommit());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit)) {
        return super.equals(obj);
      }
      com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit other = (com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit) obj;

      if (!getTypeChangesList()
          .equals(other.getTypeChangesList())) return false;
      if (hasCodeStatistics() != other.hasCodeStatistics()) return false;
      if (hasCodeStatistics()) {
        if (!getCodeStatistics()
            .equals(other.getCodeStatistics())) return false;
      }
      if (hasCommit() != other.hasCommit()) return false;
      if (hasCommit()) {
        if (!getCommit()
            .equals(other.getCommit())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTypeChangesCount() > 0) {
        hash = (37 * hash) + TYPECHANGES_FIELD_NUMBER;
        hash = (53 * hash) + getTypeChangesList().hashCode();
      }
      if (hasCodeStatistics()) {
        hash = (37 * hash) + CODESTATISTICS_FIELD_NUMBER;
        hash = (53 * hash) + getCodeStatistics().hashCode();
      }
      if (hasCommit()) {
        hash = (37 * hash) + COMMIT_FIELD_NUMBER;
        hash = (53 * hash) + getCommit().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TypeChangeCommit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TypeChangeCommit)
        com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.internal_static_TypeChangeCommit_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.internal_static_TypeChangeCommit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit.class, com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit.Builder.class);
      }

      // Construct using com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTypeChangesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (typeChangesBuilder_ == null) {
          typeChanges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          typeChangesBuilder_.clear();
        }
        if (codeStatisticsBuilder_ == null) {
          codeStatistics_ = null;
        } else {
          codeStatistics_ = null;
          codeStatisticsBuilder_ = null;
        }
        if (commitBuilder_ == null) {
          commit_ = null;
        } else {
          commit_ = null;
          commitBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.internal_static_TypeChangeCommit_descriptor;
      }

      @java.lang.Override
      public com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit getDefaultInstanceForType() {
        return com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit.getDefaultInstance();
      }

      @java.lang.Override
      public com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit build() {
        com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit buildPartial() {
        com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit result = new com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit(this);
        int from_bitField0_ = bitField0_;
        if (typeChangesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            typeChanges_ = java.util.Collections.unmodifiableList(typeChanges_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.typeChanges_ = typeChanges_;
        } else {
          result.typeChanges_ = typeChangesBuilder_.build();
        }
        if (codeStatisticsBuilder_ == null) {
          result.codeStatistics_ = codeStatistics_;
        } else {
          result.codeStatistics_ = codeStatisticsBuilder_.build();
        }
        if (commitBuilder_ == null) {
          result.commit_ = commit_;
        } else {
          result.commit_ = commitBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit) {
          return mergeFrom((com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit other) {
        if (other == com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit.getDefaultInstance()) return this;
        if (typeChangesBuilder_ == null) {
          if (!other.typeChanges_.isEmpty()) {
            if (typeChanges_.isEmpty()) {
              typeChanges_ = other.typeChanges_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTypeChangesIsMutable();
              typeChanges_.addAll(other.typeChanges_);
            }
            onChanged();
          }
        } else {
          if (!other.typeChanges_.isEmpty()) {
            if (typeChangesBuilder_.isEmpty()) {
              typeChangesBuilder_.dispose();
              typeChangesBuilder_ = null;
              typeChanges_ = other.typeChanges_;
              bitField0_ = (bitField0_ & ~0x00000001);
              typeChangesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTypeChangesFieldBuilder() : null;
            } else {
              typeChangesBuilder_.addAllMessages(other.typeChanges_);
            }
          }
        }
        if (other.hasCodeStatistics()) {
          mergeCodeStatistics(other.getCodeStatistics());
        }
        if (other.hasCommit()) {
          mergeCommit(other.getCommit());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis> typeChanges_ =
        java.util.Collections.emptyList();
      private void ensureTypeChangesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          typeChanges_ = new java.util.ArrayList<com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis>(typeChanges_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis, com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.Builder, com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysisOrBuilder> typeChangesBuilder_;

      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public java.util.List<com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis> getTypeChangesList() {
        if (typeChangesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(typeChanges_);
        } else {
          return typeChangesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public int getTypeChangesCount() {
        if (typeChangesBuilder_ == null) {
          return typeChanges_.size();
        } else {
          return typeChangesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis getTypeChanges(int index) {
        if (typeChangesBuilder_ == null) {
          return typeChanges_.get(index);
        } else {
          return typeChangesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public Builder setTypeChanges(
          int index, com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis value) {
        if (typeChangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeChangesIsMutable();
          typeChanges_.set(index, value);
          onChanged();
        } else {
          typeChangesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public Builder setTypeChanges(
          int index, com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.Builder builderForValue) {
        if (typeChangesBuilder_ == null) {
          ensureTypeChangesIsMutable();
          typeChanges_.set(index, builderForValue.build());
          onChanged();
        } else {
          typeChangesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public Builder addTypeChanges(com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis value) {
        if (typeChangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeChangesIsMutable();
          typeChanges_.add(value);
          onChanged();
        } else {
          typeChangesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public Builder addTypeChanges(
          int index, com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis value) {
        if (typeChangesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTypeChangesIsMutable();
          typeChanges_.add(index, value);
          onChanged();
        } else {
          typeChangesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public Builder addTypeChanges(
          com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.Builder builderForValue) {
        if (typeChangesBuilder_ == null) {
          ensureTypeChangesIsMutable();
          typeChanges_.add(builderForValue.build());
          onChanged();
        } else {
          typeChangesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public Builder addTypeChanges(
          int index, com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.Builder builderForValue) {
        if (typeChangesBuilder_ == null) {
          ensureTypeChangesIsMutable();
          typeChanges_.add(index, builderForValue.build());
          onChanged();
        } else {
          typeChangesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public Builder addAllTypeChanges(
          java.lang.Iterable<? extends com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis> values) {
        if (typeChangesBuilder_ == null) {
          ensureTypeChangesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, typeChanges_);
          onChanged();
        } else {
          typeChangesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public Builder clearTypeChanges() {
        if (typeChangesBuilder_ == null) {
          typeChanges_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          typeChangesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public Builder removeTypeChanges(int index) {
        if (typeChangesBuilder_ == null) {
          ensureTypeChangesIsMutable();
          typeChanges_.remove(index);
          onChanged();
        } else {
          typeChangesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.Builder getTypeChangesBuilder(
          int index) {
        return getTypeChangesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysisOrBuilder getTypeChangesOrBuilder(
          int index) {
        if (typeChangesBuilder_ == null) {
          return typeChanges_.get(index);  } else {
          return typeChangesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public java.util.List<? extends com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysisOrBuilder> 
           getTypeChangesOrBuilderList() {
        if (typeChangesBuilder_ != null) {
          return typeChangesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(typeChanges_);
        }
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.Builder addTypeChangesBuilder() {
        return getTypeChangesFieldBuilder().addBuilder(
            com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.getDefaultInstance());
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.Builder addTypeChangesBuilder(
          int index) {
        return getTypeChangesFieldBuilder().addBuilder(
            index, com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.getDefaultInstance());
      }
      /**
       * <code>repeated .TypeChangeAnalysis typeChanges = 1;</code>
       */
      public java.util.List<com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.Builder> 
           getTypeChangesBuilderList() {
        return getTypeChangesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis, com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.Builder, com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysisOrBuilder> 
          getTypeChangesFieldBuilder() {
        if (typeChangesBuilder_ == null) {
          typeChangesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis, com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysis.Builder, com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.TypeChangeAnalysisOrBuilder>(
                  typeChanges_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          typeChanges_ = null;
        }
        return typeChangesBuilder_;
      }

      private com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics codeStatistics_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics, com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics.Builder, com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatisticsOrBuilder> codeStatisticsBuilder_;
      /**
       * <code>.CodeStatistics codeStatistics = 2;</code>
       * @return Whether the codeStatistics field is set.
       */
      public boolean hasCodeStatistics() {
        return codeStatisticsBuilder_ != null || codeStatistics_ != null;
      }
      /**
       * <code>.CodeStatistics codeStatistics = 2;</code>
       * @return The codeStatistics.
       */
      public com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics getCodeStatistics() {
        if (codeStatisticsBuilder_ == null) {
          return codeStatistics_ == null ? com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics.getDefaultInstance() : codeStatistics_;
        } else {
          return codeStatisticsBuilder_.getMessage();
        }
      }
      /**
       * <code>.CodeStatistics codeStatistics = 2;</code>
       */
      public Builder setCodeStatistics(com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics value) {
        if (codeStatisticsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          codeStatistics_ = value;
          onChanged();
        } else {
          codeStatisticsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CodeStatistics codeStatistics = 2;</code>
       */
      public Builder setCodeStatistics(
          com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics.Builder builderForValue) {
        if (codeStatisticsBuilder_ == null) {
          codeStatistics_ = builderForValue.build();
          onChanged();
        } else {
          codeStatisticsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CodeStatistics codeStatistics = 2;</code>
       */
      public Builder mergeCodeStatistics(com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics value) {
        if (codeStatisticsBuilder_ == null) {
          if (codeStatistics_ != null) {
            codeStatistics_ =
              com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics.newBuilder(codeStatistics_).mergeFrom(value).buildPartial();
          } else {
            codeStatistics_ = value;
          }
          onChanged();
        } else {
          codeStatisticsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CodeStatistics codeStatistics = 2;</code>
       */
      public Builder clearCodeStatistics() {
        if (codeStatisticsBuilder_ == null) {
          codeStatistics_ = null;
          onChanged();
        } else {
          codeStatistics_ = null;
          codeStatisticsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CodeStatistics codeStatistics = 2;</code>
       */
      public com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics.Builder getCodeStatisticsBuilder() {
        
        onChanged();
        return getCodeStatisticsFieldBuilder().getBuilder();
      }
      /**
       * <code>.CodeStatistics codeStatistics = 2;</code>
       */
      public com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatisticsOrBuilder getCodeStatisticsOrBuilder() {
        if (codeStatisticsBuilder_ != null) {
          return codeStatisticsBuilder_.getMessageOrBuilder();
        } else {
          return codeStatistics_ == null ?
              com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics.getDefaultInstance() : codeStatistics_;
        }
      }
      /**
       * <code>.CodeStatistics codeStatistics = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics, com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics.Builder, com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatisticsOrBuilder> 
          getCodeStatisticsFieldBuilder() {
        if (codeStatisticsBuilder_ == null) {
          codeStatisticsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics, com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatistics.Builder, com.t2r.common.models.refactorings.CodeStatisticsOuterClass.CodeStatisticsOrBuilder>(
                  getCodeStatistics(),
                  getParentForChildren(),
                  isClean());
          codeStatistics_ = null;
        }
        return codeStatisticsBuilder_;
      }

      private com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo commit_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder> commitBuilder_;
      /**
       * <code>.CommitInfo commit = 3;</code>
       * @return Whether the commit field is set.
       */
      public boolean hasCommit() {
        return commitBuilder_ != null || commit_ != null;
      }
      /**
       * <code>.CommitInfo commit = 3;</code>
       * @return The commit.
       */
      public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo getCommit() {
        if (commitBuilder_ == null) {
          return commit_ == null ? com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.getDefaultInstance() : commit_;
        } else {
          return commitBuilder_.getMessage();
        }
      }
      /**
       * <code>.CommitInfo commit = 3;</code>
       */
      public Builder setCommit(com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo value) {
        if (commitBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          commit_ = value;
          onChanged();
        } else {
          commitBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.CommitInfo commit = 3;</code>
       */
      public Builder setCommit(
          com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder builderForValue) {
        if (commitBuilder_ == null) {
          commit_ = builderForValue.build();
          onChanged();
        } else {
          commitBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.CommitInfo commit = 3;</code>
       */
      public Builder mergeCommit(com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo value) {
        if (commitBuilder_ == null) {
          if (commit_ != null) {
            commit_ =
              com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.newBuilder(commit_).mergeFrom(value).buildPartial();
          } else {
            commit_ = value;
          }
          onChanged();
        } else {
          commitBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.CommitInfo commit = 3;</code>
       */
      public Builder clearCommit() {
        if (commitBuilder_ == null) {
          commit_ = null;
          onChanged();
        } else {
          commit_ = null;
          commitBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.CommitInfo commit = 3;</code>
       */
      public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder getCommitBuilder() {
        
        onChanged();
        return getCommitFieldBuilder().getBuilder();
      }
      /**
       * <code>.CommitInfo commit = 3;</code>
       */
      public com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder getCommitOrBuilder() {
        if (commitBuilder_ != null) {
          return commitBuilder_.getMessageOrBuilder();
        } else {
          return commit_ == null ?
              com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.getDefaultInstance() : commit_;
        }
      }
      /**
       * <code>.CommitInfo commit = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder> 
          getCommitFieldBuilder() {
        if (commitBuilder_ == null) {
          commitBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfo.Builder, com.t2r.common.models.refactorings.CommitInfoOuterClass.CommitInfoOrBuilder>(
                  getCommit(),
                  getParentForChildren(),
                  isClean());
          commit_ = null;
        }
        return commitBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TypeChangeCommit)
    }

    // @@protoc_insertion_point(class_scope:TypeChangeCommit)
    private static final com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit();
    }

    public static com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TypeChangeCommit>
        PARSER = new com.google.protobuf.AbstractParser<TypeChangeCommit>() {
      @java.lang.Override
      public TypeChangeCommit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TypeChangeCommit(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TypeChangeCommit> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TypeChangeCommit> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.t2r.common.models.refactorings.TypeChangeCommitOuterClass.TypeChangeCommit getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TypeChangeCommit_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TypeChangeCommit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026TypeChangeCommit.proto\032\030TypeChangeAnal" +
      "ysis.proto\032\024CodeStatistics.proto\032\020Commit" +
      "Info.proto\"\202\001\n\020TypeChangeCommit\022(\n\013typeC" +
      "hanges\030\001 \003(\0132\023.TypeChangeAnalysis\022\'\n\016cod" +
      "eStatistics\030\002 \001(\0132\017.CodeStatistics\022\033\n\006co" +
      "mmit\030\003 \001(\0132\013.CommitInfoB$\n\"com.t2r.commo" +
      "n.models.refactoringsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.getDescriptor(),
          com.t2r.common.models.refactorings.CodeStatisticsOuterClass.getDescriptor(),
          com.t2r.common.models.refactorings.CommitInfoOuterClass.getDescriptor(),
        });
    internal_static_TypeChangeCommit_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TypeChangeCommit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TypeChangeCommit_descriptor,
        new java.lang.String[] { "TypeChanges", "CodeStatistics", "Commit", });
    com.t2r.common.models.refactorings.TypeChangeAnalysisOuterClass.getDescriptor();
    com.t2r.common.models.refactorings.CodeStatisticsOuterClass.getDescriptor();
    com.t2r.common.models.refactorings.CommitInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
